### PR TITLE
Move jruby-openssl dependency inside an if block

### PR DESCRIPTION
**Pull request by hakanensari**
This works, gents.

### CODE REVIEW

**Comment by mattwynne** [comment]
Hakan, I'm confused by your patch, as I don't see how it changes the logic to move the if statement from an inline one to a block.

I think the basic premise of using this kind of if statement in a gemspec is flawed. When you think about it, the gemspec is evaluated when the gem is built and relased (by me, on MRI) rather than on the user's machine. 

I've now done this instead, which I think will work better:

https://github.com/mattwynne/relish/blob/c51c487a412ec02340e2fec417f4cc77483ef6df/Gemfile

This is released in 0.3.0.pre of the relish gem. Please give it a try.

**Comment by hakanensari** [comment]
Embarrassing: It seems I have higher proclivity to magical thinking.

[In a similar situation](https://github.com/papercavalier/sucker/blob/master/sucker.gemspec), I was specing against multiple platforms using RVM and somehow convinced myself that the block thing worked without giving it much thought.

Just curious: With your solution, will JRuby users have to point to the GH repo to use the library? If so, it would seem there is no way to support multiple platforms other than releasing platform-specific gems?

**Comment by mattwynne** [comment]
:)

The Gemfile is evaluated a run-time, so a jruby user (without jruby-openssl installed) sees this:

```
→ relish help
JRuby limited openssl loaded. http://jruby.org/openssl
gem install jruby-openssl for full support.
A <project> can be scoped by an organization or user handle. For
example, if an organiztion (rspec) has a project (rspec-core), then
...
```

The warning seems to be automatically generated by bundler, which is nice. RSpec does the same thing: https://github.com/rspec/rspec-core/blob/master/Gemfile#L40

**Comment by mattwynne** [comment]
Looks like the fix has worked.

**Pull request closed without merging**
